### ISSUE TITLE
startup failure

### ISSUE THREAD

**Issue by wolvre** [jieyu/maple#12]
Hi there,

When I tried the example shared_counter, maple always aborted with an OSError: No such file or directory. But if I ran the tool within a python debugger, it seems fine. Any hint for this issue?

Best,
P

**Comment by owl337** [comment]
Hi, wolvre

I get the same problem as yours. But I don't make the problem clear. Could you give more details? My issue trace is as follows.

root@ubuntu:~/Meilin/maple-master/example/shared_counter# ../../maple --- ./main 2
Traceback (most recent call last):
  File "/home/company/Meilin/maple-master/script/maple/idiom/main.py", line 1207, in <module>
    main(sys.argv[1:])
  File "/home/company/Meilin/maple-master/script/maple/idiom/main.py", line 1202, in main
    eval('__command_%s(argv[1:])' % command)
  File "<string>", line 1, in <module>
  File "/home/company/Meilin/maple-master/script/maple/idiom/main.py", line 768, in __command_default
    idiom_testcase.run()
  File "/home/company/Meilin/maple-master/script/maple/core/testing.py", line 226, in run
    self.body()
  File "/home/company/Meilin/maple-master/script/maple/idiom/testing.py", line 185, in body
    self.profile_testcase.run()
  File "/home/company/Meilin/maple-master/script/maple/core/testing.py", line 226, in run
    self.body()
  File "/home/company/Meilin/maple-master/script/maple/core/testing.py", line 257, in body
    test.run()
  File "/home/company/Meilin/maple-master/script/maple/core/testing.py", line 84, in run
    self.body()
  File "/home/company/Meilin/maple-master/script/maple/core/testing.py", line 110, in body
    stderr=self.fio[2])
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Thanks.

**Comment by wolvre** [comment]
Sorry that I don't recall much details on this problem. My earlier comment suggests to use full paths for the environment variables, e.g., PIN_HOME. Hope this can solve the problem.

**Comment by owl337** [comment]
I did use full paths.

2017-09-05 17:05 GMT+08:00 wolvre <notifications@github.com>:
